apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: viber
  namespace: viber
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: viber
    spec:
      containers:
      - name: viber
        image: aliayubkhan/susi_viberbot:latest-master
        env:
        - name: X_VIBER_AUTH_TOKEN
          value: "45a53f0fcb325002-41552d1f93cd0d0f-1a8d7fa78758d158"
        ports:
        - containerPort: 8080
