apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: viber
  namespace: viber
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: viber
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.0
        imagePullPolicy: Always
        name: viber
        ports:
        - containerPort: 8080
