apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: susi-viberbbot.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: test
          servicePort: 80
