apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-ingress
spec:
  type: LoadBalancer
  loadBalancerIP: '35.188.144.150'
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: nginx
