apiVersion: v1
kind: Service
metadata:
  name: ng
  namespace: ngi
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
  labels:
    app: ng
spec:
  type: LoadBalancer
  loadBalancerIP: '35.188.34.77'
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    k8s-app: nginx-ingress-controller
